import os
from colorama import Fore, Back, Style


def cls():
 os.system('cls' if os.name=='nt' else 'clear')

 
# let me to be free!

cls()
print(Fore.CYAN + "")


print("    _/    _/              _/                                              _/  _/              ")
print("   _/    _/    _/_/    _/_/_/_/  _/_/_/      _/_/_/    _/_/_/    _/_/_/  _/  _/    _/    _/   ")  
print("  _/_/_/_/  _/    _/    _/      _/    _/  _/    _/  _/_/      _/_/      _/_/_/_/  _/    _/    ")
print(" _/    _/  _/    _/    _/      _/    _/  _/    _/      _/_/      _/_/      _/    _/    _/     ")
print("_/    _/    _/_/        _/_/  _/_/_/      _/_/_/  _/_/_/    _/_/_/        _/      _/_/_/      ")
print("                             _/                                                               ")
print("                            _/                                                                ")
print(" ")
print(Fore.GREEN + "         by    @blackravenshackers (telegram) ")
print("")
print("")
print(Fore.CYAN + " {1} SAVE IN FILE")
print(Fore.CYAN + " {2} SHOW IN PROGRAM")
print(Fore.CYAN + " {3} DELETE OLD FILE (for 1st item)")
start = input("Choose option:")



if start == "1":
  cls()
print(Fore.CYAN + "")


print("    _/    _/              _/                                              _/  _/              ")
print("   _/    _/    _/_/    _/_/_/_/  _/_/_/      _/_/_/    _/_/_/    _/_/_/  _/  _/    _/    _/   ")  
print("  _/_/_/_/  _/    _/    _/      _/    _/  _/    _/  _/_/      _/_/      _/_/_/_/  _/    _/    ")
print(" _/    _/  _/    _/    _/      _/    _/  _/    _/      _/_/      _/_/      _/    _/    _/     ")
print("_/    _/    _/_/        _/_/  _/_/_/      _/_/_/  _/_/_/    _/_/_/        _/      _/_/_/      ")
print("                             _/                                                               ")
print("                            _/                                                                ") 
print(" ")
print(Fore.GREEN + "         by    @blackravenshackers (telegram) ")

#tut budet nachalo, eta hren
#zapizivaet v fail to chto nado
print("IF YOU DON'T KNOW ANY INFORMATION PRESS 0")
print(" ")
email = input("Type email:")
name0 = input("Name of victim:" )
secname0 = input("Lastname:" )
name1 = input("Name of victim's first child:" )
secname1 = input("Lastname of victim's first child:" )
name2 = input("Name of victim's second child:" )
secname2 = input ("Lastname of victim's second child:" )
# his or her nickname in instagram or in another app...
nickname = input("Nickname of victim:" )
age0 = input("Birthyear:" )
age1 = input("Birthmounth:" )
age2 = input("BirthDAY:" )
# first child
age3 = input("Birthyear of the first child of the victim:" )
age4 = input("Birthmounth of the first child of the victim:" )
age5 = input("BirthDAY of the first child of the victim:" )
# second child
age6 = input("Birthyear of the second child of the victim:" )
age7 = input("Birthmounth of the second child of the victim:" )
age8 = input("BirthDAY of the second child of the victim:" )
# pet name
pet0 = input("First pet:" )
pet1 = input ("Second pet:" )

cls()
 
file = open("hotpass.txt","w")
file.write(email + ":" + name0 + '\n')
file.write(email +  ":" + name0 + age0 + '\n')
file.write(email +  ":"  + age0 + name0 + '\n')
file.write(email +  ":"  + name0 + secname0 +'\n')
file.write(email +   ":" + name0 + age1 + '\n')
file.write(email +  ":"  + age1 + name0 + '\n')
file.write(email +  ":"  + name0 + secname0 + age0 + '\n')
file.write(email +   ":" + name0 + age0 + secname0 + age1 +'\n')
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n') 
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 +'\n')  
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n')   
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(email +  ":"  + name1 + '\n')
file.write(email +  ":" + name1 + age3 + '\n')
file.write(email +  ":" + age3 + name1 + '\n')
file.write(email +  ":" + name1 + secname1 +'\n')
file.write(email +  ":" + name1 + age4 + '\n')
file.write(email + ":" + age4 + name1 + '\n')
file.write(email + ":" + name1 + secname1 + age3 + '\n')
file.write(email + ":" + name1 + age3 + secname1 + age4 + '\n')
file.write(email + ":" + age3 + name1 + secname1 + age4 + age5 + '\n') 
file.write(email + ":" + age3 + name2 + secname1 + age4 + age5 + '\n')  
file.write(email + ":" + age3 + name0 + secname1 + age4 + age5 + '\n')   
file.write(email + ":" + age3 + pet1 + secname1 + age4 + age5 + '\n')  
file.write(email + ":" + age3 + pet0 + secname1 + age4 + age5 + '\n')
   
file.write(name2 + ":" + name0 + '\n')
file.write(name1 + ":" + name0 + age0 + '\n')
file.write(name0 + ":" + age0 + email + '\n')
file.write(pet0 + ":" + name0 + secname0 + '\n')
file.write(pet1 + ":" + name0 + age1 + '\n')
file.write(pet0 + ":" + age1 + name0 + '\n')
file.write(pet1 + ":" + name0 + secname0 + age0 + '\n')
file.write(pet0 + ":" + name0 + age0 + secname0 + age1 + '\n')
file.write(pet1 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n') 
file.write(pet0 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(pet1 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')   
file.write(pet0 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(name1 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(name2 + ":" + name1 + '\n')
file.write(name0 + ":" + name1 + age3 + '\n')
file.write(age0 + ":" + age3 + name1 + '\n')
file.write(age1 + ":" + name1 + secname1 +'\n')
file.write(secname0 + ":" + name1 + age4 + '\n')
file.write(secname1 + ":" + age4 + name1 + '\n')
file.write(secname2 + ":" + name1 + secname1 + age3 + '\n')
file.write(pet1 + ":" + name1 + age3 + secname1 + age4 + '\n')
file.write(pet0 + ":" + age3 + name1 + secname1 + age4 + age5 +'\n') 
file.write(secname0 + ":" + age3 + name2 + secname1 + age4 + age5 + '\n')  
file.write(secname2 + ":" + age3 + name0 + secname1 + age4 + age5 + '\n')   
file.write(secname2 + ":" + age3 + pet1 + secname1 + age4 + age5 + '\n')  
file.write(email + ":" + age3 + pet0 + secname1 + age4 + age5 + '\n')   
  
file.write(name0 + secname0 + '\n')
file.write(name0 + secname0 + age0 + '\n')
file.write(name0 + secname0 + age0 + age1 + '\n')
file.write(name0 + secname0 + age0 + age1 + age2 + '\n')
file.write(name1 + secname1 + '\n')
file.write(name2 + secname1 + '\n')
file.write(name2 + age3 + '\n')
file.write(name2 + secname2 + age2 + '\n')
file.write(name2 + secname2 + age2 + age3 + '\n')
file.write(name2 + secname2 + age2 + age3 + age4 + '\n')
file.write(name2 + secname2 + age2 + age3 + age4 + age5 + '\n')
file.write(secname2 + name2 + age2 + age3 + age4 + age5 + '\n')
file.write(secname2 + name2 + age3 + age2 + age4 + age5 + '\n')
file.write(secname1 + name1 + age3 + age2 + age4 + age5 + '\n')
file.write(secname1 + name1 + age3 + age4 + age5 + '\n')
   
   
file.write(email + ":" + secname1 + '\n')
file.write(email + ":" + name0 + secname1 + '\n')
file.write(email + ":" + age0 + name2 + '\n')
file.write(email + ":" + age1 + name2 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')
    
file.write(name2 + age1)
file.write(name2 + age1 + age2 + '\n')
file.write(name2 + age1 + age2 + age3 + '\n')
file.write(name2 + age1 + age3 + age2 + '\n')
file.write(name2 + age2 + age1 + age3 + '\n')
file.write(name2 + age2 + age3 + age1 + '\n')
file.write(name2 + age3 + age2 + age1 + '\n')
file.write(name2 + age3 + age1 + age2 + '\n')
file.write(name2 + age0 + age1 + age2 + age3 + '\n')
file.write(name2 + age0 + age1 + age3 + age2 + '\n')
file.write(name2 + age0 + age2 + age1 + age3 + '\n')
file.write(name2 + age0 + age2 + age3 + age1 + '\n')
file.write(name2 + age0 + age3 + age2 + age1 + '\n')
file.write(name2 + age0 + age3 + age1 + age2 + '\n')
file.write(name2 + age1 + age2 + age3 + age0 + '\n')
file.write(name2 + age1 + age3 + age2 + age0 + '\n')
file.write(name2 + age1 + age2 + age0 + age3 + '\n')
file.write(name2 + age1 + age3 + age0 + age2 + '\n')
file.write(name2 + age2 + age1 + age3 + age0 + '\n')
file.write(name2 + age2 + age1 + age0 + age3 + '\n')
file.write(name2 + age2 + age0 + age1 + age3 + '\n')
file.write(name2 + age2 + age0 + age3 + age1 + '\n')
file.write(name2 + age2 + age3 + age1 + age0 + '\n')
file.write(name2 + age2 + age3 + age0 + age1 + '\n')
file.write(name2 + age3 + age2 + age1 + age0 + '\n')
file.write(name2 + age3 + age2 + age0 + age1 + '\n')
file.write(name2 + age3 + age1 + age0 + age2 + '\n')
file.write(name2 + age3 + age1 + age2 + age0 + '\n')
file.write(name2 + age3 + age0 + age2 + age1 + '\n')
file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
file.write(pet1 + age1 + '\n')
file.write(pet1 + age1 + age2 + '\n')
file.write(pet1 + age1 + age2 + age3 + '\n')
file.write(pet1 + age1 + age3 + age2 + '\n')
file.write(pet1 + age2 + age1 + age3 + '\n')
file.write(pet1 + age2 + age3 + age1 + '\n')
file.write(pet1 + age3 + age2 + age1 + '\n')
file.write(pet1 + age3 + age1 + age2 + '\n')
file.write(pet1 + age0 + age1 + age2 + age3 + '\n')
file.write(pet1 + age0 + age1 + age3 + age2 + '\n')
file.write(pet1 + age0 + age2 + age1 + age3 + '\n')
file.write(pet1 + age0 + age2 + age3 + age1 + '\n')
file.write(pet1 + age0 + age3 + age2 + age1 + '\n')
file.write(pet1 + age0 + age3 + age1 + age2 + '\n')
file.write(pet1 + age1 + age2 + age3 + age0 + '\n')
file.write(pet0 + age1 + age3 + age2 + age0 + '\n')
file.write(pet0 + age1 + age2 + age0 + age3 + '\n')
file.write(pet0 + age1 + age3 + age0 + age2 + '\n')
file.write(pet0 + age2 + age1 + age3 + age0 + '\n')
file.write(pet0 + age2 + age1 + age0 + age3 + '\n')
file.write(pet0 + age2 + age0 + age1 + age3 + '\n')
file.write(pet0 + age2 + age0 + age3 + age1 + '\n')
file.write(pet0 + age2 + age3 + age1 + age0 + '\n')
file.write(pet0 + age2 + age3 + age0 + age1 + '\n')
file.write(pet0 + age3 + age2 + age1 + age0 + '\n')
file.write(pet0 + age3 + age2 + age0 + age1 + '\n')
file.write(pet0 + age3 + age1 + age0 + age2 + '\n')
file.write(pet0 + age3 + age1 + age2 + age0 + '\n')
file.write(pet0 + age3 + age0 + age2 + age1 + '\n')
file.write(pet0 + age3 + age0 + age1 + age2 + '\n')
file.write(email + ":" + name0 + '\n')
file.write(email + ":" + name1 + '\n')
file.write(email + ":" + name0 + secname1 + '\n')
file.write(email + ":" + age0 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')

file.write(name1 + age1 + '\n')
file.write(name1 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + '\n')
file.write(name1 + age1 + age3 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + '\n')
file.write(name1 + age2 + age3 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + '\n')
file.write(name1 + age3 + age1 + age2 + '\n')
file.write(name1 + age0 + age1 + age2 + age3 + '\n')
file.write(name1 + age0 + age1 + age3 + age2 + '\n')
file.write(name1 + age0 + age2 + age1 + age3 + '\n')
file.write(name1 + age0 + age2 + age3 + age1 + '\n')
file.write(name1 + age0 + age3 + age2 + age1 + '\n')
file.write(name1 + age0 + age3 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + age0 + '\n')
file.write(name1 + age1 + age3 + age2 + age0 + '\n')
file.write(name1 + age1 + age2 + age0 + age3 + '\n')
file.write(name1 + age1 + age3 + age0 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + age0 + '\n')
file.write(name1 + age2 + age1 + age0 + age3 + '\n')
file.write(name1 + age2 + age0 + age1 + age3 + '\n')
file.write(name1 + age2 + age0 + age3 + age1 + '\n')
file.write(name1 + age2 + age3 + age1 + age0 + '\n')
file.write(name1 + age2 + age3 + age0 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + age0 + '\n')
file.write(name1 + age3 + age2 + age0 + age1 + '\n')
file.write(name1 + age3 + age1 + age0 + age2 + '\n')
file.write(name1 + age3 + age1 + age2 + age0 + '\n')
file.write(name1 + age3 + age0 + age2 + age1 + '\n')
file.write(name1 + age3 + age0 + age1 + age2 + '\n')

file.write(email + ":" + secname0 + '\n')
file.write(email + ":" + secname0 + secname1 + '\n')
file.write(email + ":" + secname0 + secname1 + secname2 + '\n')
file.write(email + ":" + secname0 + secname2 + secname1 + '\n')
file.write(email + ":" + pet0 + '\n')
file.write(email + ":" + pet1 + '\n')
file.write(name1 + age1 + '\n')
file.write(name1 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + '\n')
file.write(name1 + age1 + age3 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + '\n')
file.write(name1 + age2 + age3 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + '\n')
file.write(name1 + age3 + age1 + age2 + '\n')
file.write(name1 + age0 + age1 + age2 + age3 + '\n')
file.write(name1 + age0 + age1 + age3 + age2 + '\n')
file.write(name1 + age0 + age2 + age1 + age3 + '\n')
file.write(name1 + age0 + age2 + age3 + age1 + '\n')
file.write(name1 + age0 + age3 + age2 + age1 + '\n')
file.write(name1 + age0 + age3 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + age0 + '\n')
file.write(name1 + age1 + age3 + age2 + age0 + '\n')
file.write(name1 + age1 + age2 + age0 + age3 + '\n')
file.write(name1 + age1 + age3 + age0 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + age0 + '\n')
file.write(name1 + age2 + age1 + age0 + age3 + '\n')
file.write(name1 + age2 + age0 + age1 + age3 + '\n')
file.write(name1 + age2 + age0 + age3 + age1 + '\n')
file.write(name1 + age2 + age3 + age1 + age0 + '\n')
file.write(name1 + age2 + age3 + age0 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + age0 + '\n')
file.write(name1 + age3 + age2 + age0 + age1 + '\n')
file.write(name1 + age3 + age1 + age0 + age2 + '\n')
file.write(name1 + age3 + age1 + age2 + age0 + '\n')
file.write(name1 + age3 + age0 + age2 + age1 + '\n')
file.write(name1 + age3 + age0 + age1 + age2 + '\n')

file.write(email + ":" + name1 + '\n')
file.write(email + ":" + name1 + secname1 + '\n')
file.write(email + ":" + age0 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')
file.write(email + ":" + secname0 + '\n')
file.write(email + ":" + name1 + '\n')
file.write(email + ":" + name1 + secname1 + '\n')
file.write(email + ":" + age0 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')

file.write(name1 + age1 + '\n')
file.write(name1 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + '\n')
file.write(name1 + age1 + age3 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + '\n')
file.write(name1 + age2 + age3 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + '\n')
file.write(name1 + age3 + age1 + age2 + '\n')
file.write(name1 + age0 + age1 + age2 + age3 + '\n')
file.write(name1 + age0 + age1 + age3 + age2 + '\n')
file.write(name1 + age0 + age2 + age1 + age3 + '\n')
file.write(name1 + age0 + age2 + age3 + age1 + '\n')
file.write(name1 + age0 + age3 + age2 + age1 + '\n')
file.write(name1 + age0 + age3 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + age0 + '\n')
file.write(name1 + age1 + age3 + age2 + age0 + '\n')
file.write(name1 + age1 + age2 + age0 + age3 + '\n')
file.write(name1 + age1 + age3 + age0 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + age0 + '\n')
file.write(name1 + age2 + age1 + age0 + age3 + '\n')
file.write(name1 + age2 + age0 + age1 + age3 + '\n')
file.write(name1 + age2 + age0 + age3 + age1 + '\n')
file.write(name1 + age2 + age3 + age1 + age0 + '\n')
file.write(name1 + age2 + age3 + age0 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + age0 + '\n')
file.write(name1 + age3 + age2 + age0 + age1 + '\n')
file.write(name1 + age3 + age1 + age0 + age2 + '\n')
file.write(name1 + age3 + age1 + age2 + age0 + '\n')
file.write(name1 + age3 + age0 + age2 + age1 + '\n')
file.write(name1 + age3 + age0 + age1 + age2 + '\n')  
  
if name0 == "0":
    file.write(email + secname0 + '\n')
    file.write(email +  secname0 + secname1 + '\n')
    file.write(email +  secname0 + secname1 + secname2 + '\n')
    file.write(email +  secname0 + secname2 + secname1 + '\n')
    file.write(email +  pet0 + '\n')
    file.write(email + pet1 + '\n')
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')

    file.write(email +  name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0 + '\n' )
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    file.write(email + secname0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0  + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')

    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')

if secname0 == "0":
    file.write(email + name0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')
if name1 == "0":
    file.write(email + name0 + '\n')
    file.write(email + secname1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + name2 + '\n')
    file.write(email + age1 + name2 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name2 + age1 + '\n')
    file.write(name2 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + '\n')
    file.write(name2 + age1 + age3 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + '\n')
    file.write(name2 + age2 + age3 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + '\n')
    file.write(name2 + age3 + age1 + age2 + '\n')
    file.write(name2 + age0 + age1 + age2 + age3 + '\n')
    file.write(name2 + age0 + age1 + age3 + age2 + '\n')
    file.write(name2 + age0 + age2 + age1 + age3 + '\n')
    file.write(name2 + age0 + age2 + age3 + age1 + '\n')
    file.write(name2 + age0 + age3 + age2 + age1 + '\n')
    file.write(name2 + age0 + age3 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + age0 + '\n')
    file.write(name2 + age1 + age3 + age2 + age0 + '\n')
    file.write(name2 + age1 + age2 + age0 + age3 + '\n')
    file.write(name2 + age1 + age3 + age0 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + age0 + '\n')
    file.write(name2 + age2 + age1 + age0 + age3 + '\n')
    file.write(name2 + age2 + age0 + age1 + age3 + '\n')
    file.write(name2 + age2 + age0 + age3 + age1 + '\n')
    file.write(name2 + age2 + age3 + age1 + age0 + '\n')
    file.write(name2 + age2 + age3 + age0 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + age0 + '\n')
    file.write(name2 + age3 + age2 + age0 + age1 + '\n')
    file.write(name2 + age3 + age1 + age0 + age2 + '\n')
    file.write(name2 + age3 + age1 + age2 + age0 + '\n')
    file.write(name2 + age3 + age0 + age2 + age1 + '\n')
    file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(name0 + age1 + '\n')
    file.write(name0 + age1 + age2 + '\n')
    file.write(name0 + age1 + age2 + age3 + '\n')
    file.write(name0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name3 + age2 + age3 + age1 + '\n')
    file.write(name3 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + age0 + '\n')
    file.write(name2 + age2 + age1 + age0 + age3 + '\n')
    file.write(name2 + age2 + age0 + age1 + age3 + '\n')
    file.write(name2 + age2 + age0 + age3 + age1 + '\n')
    file.write(name2 + age2 + age3 + age1 + age0 + '\n')
    file.write(name2 + age2 + age3 + age0 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + age0 + '\n')
    file.write(name2 + age3 + age2 + age0 + age1 + '\n')
    file.write(name2 + age3 + age1 + age0 + age2 + '\n')
    file.write(name2 + age3 + age1 + age2 + age0 + '\n')
    file.write(name2 + age3 + age0 + age2 + age1 + '\n')
    file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
    
    
    
   
 
else:
    file.write(name0 + secname0 + '\n')
    file.write(name0 + secname0 + age0 + '\n')
    file.write(name0 + secname0 + age0 + age1 + '\n')
    file.write(name0 + secname0 + age0 + age1 + age2 + '\n')
    file.write(name1 + secname1 + '\n')
    file.write(name2 + secname1 + '\n')
    file.write(name2 + age3 + '\n')
    file.write(name2 + secname2 + age2 + '\n')
    file.write(name2 + secname2 + age2 + age3 + '\n')
    file.write(name2 + secname2 + age2 + age3 + age4 + '\n')
    file.write(name2 + secname2 + age2 + age3 + age4 + age5 + '\n')
    file.write(secname2 + name2 + age2 + age3 + age4 + age5 + '\n')
    file.write(secname2 + name2 + age3 + age2 + age4 + age5 + '\n')
    file.write(secname1 + name1 + age3 + age2 + age4 + age5 + '\n')
    file.write(secname1 + name1 + age3 + age4 + age5 + '\n')
   
   
    file.write(email + secname1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + name2 + '\n')
    file.write(email + age1 + name2 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name2 + age1 + '\n')
    file.write(name2 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + '\n')
    file.write(name2 + age1 + age3 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + '\n')
    file.write(name2 + age2 + age3 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + '\n')
    file.write(name2 + age3 + age1 + age2 + '\n')
    file.write(name2 + age0 + age1 + age2 + age3 + '\n')
    file.write(name2 + age0 + age1 + age3 + age2 + '\n')
    file.write(name2 + age0 + age2 + age1 + age3 + '\n')
    file.write(name2 + age0 + age2 + age3 + age1 + '\n')
    file.write(name2 + age0 + age3 + age2 + age1 + '\n')
    file.write(name2 + age0 + age3 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + age0 + '\n')
    file.write(name2 + age1 + age3 + age2 + age0 + '\n')
    file.write(name2 + age1 + age2 + age0 + age3 + '\n')
    file.write(name2 + age1 + age3 + age0 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + age0 + '\n')
    file.write(name2 + age2 + age1 + age0 + age3 + '\n')
    file.write(name2 + age2 + age0 + age1 + age3 + '\n')
    file.write(name2 + age2 + age0 + age3 + age1 + '\n')
    file.write(name2 + age2 + age3 + age1 + age0 + '\n')
    file.write(name2 + age2 + age3 + age0 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + age0 + '\n')
    file.write(name2 + age3 + age2 + age0 + age1 + '\n')
    file.write(name2 + age3 + age1 + age0 + age2 + '\n')
    file.write(name2 + age3 + age1 + age2 + age0 + '\n')
    file.write(name2 + age3 + age0 + age2 + age1 + '\n')
    file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(pet1 + age1 + '\n')
    file.write(pet1 + age1 + age2 + '\n')
    file.write(pet1 + age1 + age2 + age3 + '\n')
    file.write(pet1 + age1 + age3 + age2 + '\n')
    file.write(pet1 + age2 + age1 + age3 + '\n')
    file.write(pet1 + age2 + age3 + age1 + '\n')
    file.write(pet1 + age3 + age2 + age1 + '\n')
    file.write(pet1 + age3 + age1 + age2 + '\n')
    file.write(pet1 + age0 + age1 + age2 + age3 + '\n')
    file.write(pet1 + age0 + age1 + age3 + age2 + '\n')
    file.write(pet1 + age0 + age2 + age1 + age3 + '\n')
    file.write(pet1 + age0 + age2 + age3 + age1 + '\n')
    file.write(pet1 + age0 + age3 + age2 + age1 + '\n')
    file.write(pet1 + age0 + age3 + age1 + age2 + '\n')
    file.write(pet1 + age1 + age2 + age3 + age0 + '\n')
    file.write(pet0 + age1 + age3 + age2 + age0 + '\n')
    file.write(pet0 + age1 + age2 + age0 + age3 + '\n')
    file.write(pet0 + age1 + age3 + age0 + age2 + '\n')
    file.write(pet0 + age2 + age1 + age3 + age0 + '\n')
    file.write(pet0 + age2 + age1 + age0 + age3 + '\n')
    file.write(pet0 + age2 + age0 + age1 + age3 + '\n')
    file.write(pet0 + age2 + age0 + age3 + age1 + '\n')
    file.write(pet0 + age2 + age3 + age1 + age0 + '\n')
    file.write(pet0 + age2 + age3 + age0 + age1 + '\n')
    file.write(pet0 + age3 + age2 + age1 + age0 + '\n')
    file.write(pet0 + age3 + age2 + age0 + age1 + '\n')
    file.write(pet0 + age3 + age1 + age0 + age2 + '\n')
    file.write(pet0 + age3 + age1 + age2 + age0 + '\n')
    file.write(pet0 + age3 + age0 + age2 + age1 + '\n')
    file.write(pet0 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(email + name0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(email + secname0 + '\n')
    file.write(email + secname0 + secname1 + '\n')
    file.write(email + secname0 + secname1 + secname2 + '\n')
    file.write(email + secname0 + secname2 + secname1 + '\n')
    file.write(email + pet0 + '\n')
    file.write(email + pet1 + '\n')
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(email + name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    file.write(email + secname0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')
    
    
if start == "2":
  cls()
print(Fore.CYAN + " ")


print("    _/    _/              _/                                              _/  _/              ")
print("   _/    _/    _/_/    _/_/_/_/  _/_/_/      _/_/_/    _/_/_/    _/_/_/  _/  _/    _/    _/   ")  
print("  _/_/_/_/  _/    _/    _/      _/    _/  _/    _/  _/_/      _/_/      _/_/_/_/  _/    _/    ")
print(" _/    _/  _/    _/    _/      _/    _/  _/    _/      _/_/      _/_/      _/    _/    _/     ")
print("_/    _/    _/_/        _/_/  _/_/_/      _/_/_/  _/_/_/    _/_/_/        _/      _/_/_/      ")
print("                             _/                                                               ")
print("                            _/                                                                ") 
print(" ")
print(Fore.GREEN + "         by    @blackravenshackers (telegram) ")

#tut budet pochti konec, eta hren
#zapizivaet v fail to chto nado
print("IF YOU DON'T KNOW ANY INFORMATION PRESS 0")
print(" ")
email = input("Type email:")
name0 = input("Name of victim:" )
secname0 = input("Lastname:" )
name1 = input("Name of victim's first child:" )
secname1 = input("Lastname of victim's first child:" )
name2 = input("Name of victim's second child:" )
secname2 = input ("Lastname of victim's second child:" )
# his or her nickname in instagram or in another app...
nickname = input("Nickname of victim:" )
age0 = input("Birthyear:" )
age1 = input("Birthmounth:" )
age2 = input("BirthDAY:" )
# first child
age3 = input("Birthyear of the first child of the victim:" )
age4 = input("Birthmounth of the first child of the victim:" )
age5 = input("BirthDAY of the first child of the victim:" )
# second child
age6 = input("Birthyear of the second child of the victim:" )
age7 = input("Birthmounth of the second child of the victim:" )
age8 = input("BirthDAY of the second child of the victim:" )
# pet name
pet0 = input("First pet:" )
pet1 = input ("Second pet:" )

cls()
 
file = open("hotpass.txt","w")
file.write(email + ":" + name0 + '\n')
file.write(email +  ":" + name0 + age0 + '\n')
file.write(email +  ":"  + age0 + name0 + '\n')
file.write(email +  ":"  + name0 + secname0 +'\n')
file.write(email +   ":" + name0 + age1 + '\n')
file.write(email +  ":"  + age1 + name0 + '\n')
file.write(email +  ":"  + name0 + secname0 + age0 + '\n')
file.write(email +   ":" + name0 + age0 + secname0 + age1 +'\n')
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n') 
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 +'\n')  
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n')   
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(email +  ":"  + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(email +  ":"  + name1 + '\n')
file.write(email +  ":" + name1 + age3 + '\n')
file.write(email +  ":" + age3 + name1 + '\n')
file.write(email +  ":" + name1 + secname1 +'\n')
file.write(email +  ":" + name1 + age4 + '\n')
file.write(email + ":" + age4 + name1 + '\n')
file.write(email + ":" + name1 + secname1 + age3 + '\n')
file.write(email + ":" + name1 + age3 + secname1 + age4 + '\n')
file.write(email + ":" + age3 + name1 + secname1 + age4 + age5 + '\n') 
file.write(email + ":" + age3 + name2 + secname1 + age4 + age5 + '\n')  
file.write(email + ":" + age3 + name0 + secname1 + age4 + age5 + '\n')   
file.write(email + ":" + age3 + pet1 + secname1 + age4 + age5 + '\n')  
file.write(email + ":" + age3 + pet0 + secname1 + age4 + age5 + '\n')
   
file.write(name2 + ":" + name0 + '\n')
file.write(name1 + ":" + name0 + age0 + '\n')
file.write(name0 + ":" + age0 + email + '\n')
file.write(pet0 + ":" + name0 + secname0 + '\n')
file.write(pet1 + ":" + name0 + age1 + '\n')
file.write(pet0 + ":" + age1 + name0 + '\n')
file.write(pet1 + ":" + name0 + secname0 + age0 + '\n')
file.write(pet0 + ":" + name0 + age0 + secname0 + age1 + '\n')
file.write(pet1 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n') 
file.write(pet0 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(pet1 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')   
file.write(pet0 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(name1 + ":" + age0 + name0 + secname0 + age1 + age2 + '\n')  
file.write(name2 + ":" + name1 + '\n')
file.write(name0 + ":" + name1 + age3 + '\n')
file.write(age0 + ":" + age3 + name1 + '\n')
file.write(age1 + ":" + name1 + secname1 +'\n')
file.write(secname0 + ":" + name1 + age4 + '\n')
file.write(secname1 + ":" + age4 + name1 + '\n')
file.write(secname2 + ":" + name1 + secname1 + age3 + '\n')
file.write(pet1 + ":" + name1 + age3 + secname1 + age4 + '\n')
file.write(pet0 + ":" + age3 + name1 + secname1 + age4 + age5 +'\n') 
file.write(secname0 + ":" + age3 + name2 + secname1 + age4 + age5 + '\n')  
file.write(secname2 + ":" + age3 + name0 + secname1 + age4 + age5 + '\n')   
file.write(secname2 + ":" + age3 + pet1 + secname1 + age4 + age5 + '\n')  
file.write(email + ":" + age3 + pet0 + secname1 + age4 + age5 + '\n')   
  
file.write(name0 + secname0 + '\n')
file.write(name0 + secname0 + age0 + '\n')
file.write(name0 + secname0 + age0 + age1 + '\n')
file.write(name0 + secname0 + age0 + age1 + age2 + '\n')
file.write(name1 + secname1 + '\n')
file.write(name2 + secname1 + '\n')
file.write(name2 + age3 + '\n')
file.write(name2 + secname2 + age2 + '\n')
file.write(name2 + secname2 + age2 + age3 + '\n')
file.write(name2 + secname2 + age2 + age3 + age4 + '\n')
file.write(name2 + secname2 + age2 + age3 + age4 + age5 + '\n')
file.write(secname2 + name2 + age2 + age3 + age4 + age5 + '\n')
file.write(secname2 + name2 + age3 + age2 + age4 + age5 + '\n')
file.write(secname1 + name1 + age3 + age2 + age4 + age5 + '\n')
file.write(secname1 + name1 + age3 + age4 + age5 + '\n')
   
   
file.write(email + ":" + secname1 + '\n')
file.write(email + ":" + name0 + secname1 + '\n')
file.write(email + ":" + age0 + name2 + '\n')
file.write(email + ":" + age1 + name2 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')
    
file.write(name2 + age1)
file.write(name2 + age1 + age2 + '\n')
file.write(name2 + age1 + age2 + age3 + '\n')
file.write(name2 + age1 + age3 + age2 + '\n')
file.write(name2 + age2 + age1 + age3 + '\n')
file.write(name2 + age2 + age3 + age1 + '\n')
file.write(name2 + age3 + age2 + age1 + '\n')
file.write(name2 + age3 + age1 + age2 + '\n')
file.write(name2 + age0 + age1 + age2 + age3 + '\n')
file.write(name2 + age0 + age1 + age3 + age2 + '\n')
file.write(name2 + age0 + age2 + age1 + age3 + '\n')
file.write(name2 + age0 + age2 + age3 + age1 + '\n')
file.write(name2 + age0 + age3 + age2 + age1 + '\n')
file.write(name2 + age0 + age3 + age1 + age2 + '\n')
file.write(name2 + age1 + age2 + age3 + age0 + '\n')
file.write(name2 + age1 + age3 + age2 + age0 + '\n')
file.write(name2 + age1 + age2 + age0 + age3 + '\n')
file.write(name2 + age1 + age3 + age0 + age2 + '\n')
file.write(name2 + age2 + age1 + age3 + age0 + '\n')
file.write(name2 + age2 + age1 + age0 + age3 + '\n')
file.write(name2 + age2 + age0 + age1 + age3 + '\n')
file.write(name2 + age2 + age0 + age3 + age1 + '\n')
file.write(name2 + age2 + age3 + age1 + age0 + '\n')
file.write(name2 + age2 + age3 + age0 + age1 + '\n')
file.write(name2 + age3 + age2 + age1 + age0 + '\n')
file.write(name2 + age3 + age2 + age0 + age1 + '\n')
file.write(name2 + age3 + age1 + age0 + age2 + '\n')
file.write(name2 + age3 + age1 + age2 + age0 + '\n')
file.write(name2 + age3 + age0 + age2 + age1 + '\n')
file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
file.write(pet1 + age1 + '\n')
file.write(pet1 + age1 + age2 + '\n')
file.write(pet1 + age1 + age2 + age3 + '\n')
file.write(pet1 + age1 + age3 + age2 + '\n')
file.write(pet1 + age2 + age1 + age3 + '\n')
file.write(pet1 + age2 + age3 + age1 + '\n')
file.write(pet1 + age3 + age2 + age1 + '\n')
file.write(pet1 + age3 + age1 + age2 + '\n')
file.write(pet1 + age0 + age1 + age2 + age3 + '\n')
file.write(pet1 + age0 + age1 + age3 + age2 + '\n')
file.write(pet1 + age0 + age2 + age1 + age3 + '\n')
file.write(pet1 + age0 + age2 + age3 + age1 + '\n')
file.write(pet1 + age0 + age3 + age2 + age1 + '\n')
file.write(pet1 + age0 + age3 + age1 + age2 + '\n')
file.write(pet1 + age1 + age2 + age3 + age0 + '\n')
file.write(pet0 + age1 + age3 + age2 + age0 + '\n')
file.write(pet0 + age1 + age2 + age0 + age3 + '\n')
file.write(pet0 + age1 + age3 + age0 + age2 + '\n')
file.write(pet0 + age2 + age1 + age3 + age0 + '\n')
file.write(pet0 + age2 + age1 + age0 + age3 + '\n')
file.write(pet0 + age2 + age0 + age1 + age3 + '\n')
file.write(pet0 + age2 + age0 + age3 + age1 + '\n')
file.write(pet0 + age2 + age3 + age1 + age0 + '\n')
file.write(pet0 + age2 + age3 + age0 + age1 + '\n')
file.write(pet0 + age3 + age2 + age1 + age0 + '\n')
file.write(pet0 + age3 + age2 + age0 + age1 + '\n')
file.write(pet0 + age3 + age1 + age0 + age2 + '\n')
file.write(pet0 + age3 + age1 + age2 + age0 + '\n')
file.write(pet0 + age3 + age0 + age2 + age1 + '\n')
file.write(pet0 + age3 + age0 + age1 + age2 + '\n')
file.write(email + ":" + name0 + '\n')
file.write(email + ":" + name1 + '\n')
file.write(email + ":" + name0 + secname1 + '\n')
file.write(email + ":" + age0 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')

file.write(name1 + age1 + '\n')
file.write(name1 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + '\n')
file.write(name1 + age1 + age3 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + '\n')
file.write(name1 + age2 + age3 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + '\n')
file.write(name1 + age3 + age1 + age2 + '\n')
file.write(name1 + age0 + age1 + age2 + age3 + '\n')
file.write(name1 + age0 + age1 + age3 + age2 + '\n')
file.write(name1 + age0 + age2 + age1 + age3 + '\n')
file.write(name1 + age0 + age2 + age3 + age1 + '\n')
file.write(name1 + age0 + age3 + age2 + age1 + '\n')
file.write(name1 + age0 + age3 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + age0 + '\n')
file.write(name1 + age1 + age3 + age2 + age0 + '\n')
file.write(name1 + age1 + age2 + age0 + age3 + '\n')
file.write(name1 + age1 + age3 + age0 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + age0 + '\n')
file.write(name1 + age2 + age1 + age0 + age3 + '\n')
file.write(name1 + age2 + age0 + age1 + age3 + '\n')
file.write(name1 + age2 + age0 + age3 + age1 + '\n')
file.write(name1 + age2 + age3 + age1 + age0 + '\n')
file.write(name1 + age2 + age3 + age0 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + age0 + '\n')
file.write(name1 + age3 + age2 + age0 + age1 + '\n')
file.write(name1 + age3 + age1 + age0 + age2 + '\n')
file.write(name1 + age3 + age1 + age2 + age0 + '\n')
file.write(name1 + age3 + age0 + age2 + age1 + '\n')
file.write(name1 + age3 + age0 + age1 + age2 + '\n')

file.write(email + ":" + secname0 + '\n')
file.write(email + ":" + secname0 + secname1 + '\n')
file.write(email + ":" + secname0 + secname1 + secname2 + '\n')
file.write(email + ":" + secname0 + secname2 + secname1 + '\n')
file.write(email + ":" + pet0 + '\n')
file.write(email + ":" + pet1 + '\n')
file.write(name1 + age1 + '\n')
file.write(name1 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + '\n')
file.write(name1 + age1 + age3 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + '\n')
file.write(name1 + age2 + age3 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + '\n')
file.write(name1 + age3 + age1 + age2 + '\n')
file.write(name1 + age0 + age1 + age2 + age3 + '\n')
file.write(name1 + age0 + age1 + age3 + age2 + '\n')
file.write(name1 + age0 + age2 + age1 + age3 + '\n')
file.write(name1 + age0 + age2 + age3 + age1 + '\n')
file.write(name1 + age0 + age3 + age2 + age1 + '\n')
file.write(name1 + age0 + age3 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + age0 + '\n')
file.write(name1 + age1 + age3 + age2 + age0 + '\n')
file.write(name1 + age1 + age2 + age0 + age3 + '\n')
file.write(name1 + age1 + age3 + age0 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + age0 + '\n')
file.write(name1 + age2 + age1 + age0 + age3 + '\n')
file.write(name1 + age2 + age0 + age1 + age3 + '\n')
file.write(name1 + age2 + age0 + age3 + age1 + '\n')
file.write(name1 + age2 + age3 + age1 + age0 + '\n')
file.write(name1 + age2 + age3 + age0 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + age0 + '\n')
file.write(name1 + age3 + age2 + age0 + age1 + '\n')
file.write(name1 + age3 + age1 + age0 + age2 + '\n')
file.write(name1 + age3 + age1 + age2 + age0 + '\n')
file.write(name1 + age3 + age0 + age2 + age1 + '\n')
file.write(name1 + age3 + age0 + age1 + age2 + '\n')

file.write(email + ":" + name1 + '\n')
file.write(email + ":" + name1 + secname1 + '\n')
file.write(email + ":" + age0 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')
file.write(email + ":" + secname0 + '\n')
file.write(email + ":" + name1 + '\n')
file.write(email + ":" + name1 + secname1 + '\n')
file.write(email + ":" + age0 + '\n')
file.write(email + ":" + age0 + age1 + '\n')
file.write(email + ":" + age0 + age1 + age2 + '\n')
file.write(email + ":" + age0 + age2 + age1 + '\n')
file.write(email + ":" + age1 + age0 + age2 + '\n')
file.write(email + ":" + age1 + age2 + age0 + '\n')
file.write(email + ":" + age2 + age0 + age1 + '\n')
file.write(email + ":" + age2 + age1 + age0 + '\n')
file.write(email + ":" + age3 + age4 + age5 + '\n')
file.write(email + ":" + age3 + age5 + age4 + '\n')
file.write(email + ":" + age4 + age3 + age5 + '\n')
file.write(email + ":" + age4 + age5 + age3 + '\n')
file.write(email + ":" + age5 + age3 + age4 + '\n')
file.write(email + ":" + age5 + age4 + age3 + '\n')
file.write(email + ":" + age6 + age7 + age8 + '\n')
file.write(email + ":" + age6 + age8 + age7 + '\n')
file.write(email + ":" + age7 + age8 + age6 + '\n')
file.write(email + ":" + age7 + age6 + age8 + '\n')
file.write(email + ":" + age8 + age6 + age7 + '\n')
file.write(email + ":" + age8 + age7 + age6 + '\n')

file.write(name1 + age1 + '\n')
file.write(name1 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + '\n')
file.write(name1 + age1 + age3 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + '\n')
file.write(name1 + age2 + age3 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + '\n')
file.write(name1 + age3 + age1 + age2 + '\n')
file.write(name1 + age0 + age1 + age2 + age3 + '\n')
file.write(name1 + age0 + age1 + age3 + age2 + '\n')
file.write(name1 + age0 + age2 + age1 + age3 + '\n')
file.write(name1 + age0 + age2 + age3 + age1 + '\n')
file.write(name1 + age0 + age3 + age2 + age1 + '\n')
file.write(name1 + age0 + age3 + age1 + age2 + '\n')
file.write(name1 + age1 + age2 + age3 + age0 + '\n')
file.write(name1 + age1 + age3 + age2 + age0 + '\n')
file.write(name1 + age1 + age2 + age0 + age3 + '\n')
file.write(name1 + age1 + age3 + age0 + age2 + '\n')
file.write(name1 + age2 + age1 + age3 + age0 + '\n')
file.write(name1 + age2 + age1 + age0 + age3 + '\n')
file.write(name1 + age2 + age0 + age1 + age3 + '\n')
file.write(name1 + age2 + age0 + age3 + age1 + '\n')
file.write(name1 + age2 + age3 + age1 + age0 + '\n')
file.write(name1 + age2 + age3 + age0 + age1 + '\n')
file.write(name1 + age3 + age2 + age1 + age0 + '\n')
file.write(name1 + age3 + age2 + age0 + age1 + '\n')
file.write(name1 + age3 + age1 + age0 + age2 + '\n')
file.write(name1 + age3 + age1 + age2 + age0 + '\n')
file.write(name1 + age3 + age0 + age2 + age1 + '\n')
file.write(name1 + age3 + age0 + age1 + age2 + '\n')  
  
if name0 == "0":
    file.write(email + secname0 + '\n')
    file.write(email +  secname0 + secname1 + '\n')
    file.write(email +  secname0 + secname1 + secname2 + '\n')
    file.write(email +  secname0 + secname2 + secname1 + '\n')
    file.write(email +  pet0 + '\n')
    file.write(email + pet1 + '\n')
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')

    file.write(email +  name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0 + '\n' )
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    file.write(email + secname0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0  + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')

    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')

if secname0 == "0":
    file.write(email + name0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')
if name1 == "0":
    file.write(email + name0 + '\n')
    file.write(email + secname1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + name2 + '\n')
    file.write(email + age1 + name2 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name2 + age1 + '\n')
    file.write(name2 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + '\n')
    file.write(name2 + age1 + age3 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + '\n')
    file.write(name2 + age2 + age3 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + '\n')
    file.write(name2 + age3 + age1 + age2 + '\n')
    file.write(name2 + age0 + age1 + age2 + age3 + '\n')
    file.write(name2 + age0 + age1 + age3 + age2 + '\n')
    file.write(name2 + age0 + age2 + age1 + age3 + '\n')
    file.write(name2 + age0 + age2 + age3 + age1 + '\n')
    file.write(name2 + age0 + age3 + age2 + age1 + '\n')
    file.write(name2 + age0 + age3 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + age0 + '\n')
    file.write(name2 + age1 + age3 + age2 + age0 + '\n')
    file.write(name2 + age1 + age2 + age0 + age3 + '\n')
    file.write(name2 + age1 + age3 + age0 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + age0 + '\n')
    file.write(name2 + age2 + age1 + age0 + age3 + '\n')
    file.write(name2 + age2 + age0 + age1 + age3 + '\n')
    file.write(name2 + age2 + age0 + age3 + age1 + '\n')
    file.write(name2 + age2 + age3 + age1 + age0 + '\n')
    file.write(name2 + age2 + age3 + age0 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + age0 + '\n')
    file.write(name2 + age3 + age2 + age0 + age1 + '\n')
    file.write(name2 + age3 + age1 + age0 + age2 + '\n')
    file.write(name2 + age3 + age1 + age2 + age0 + '\n')
    file.write(name2 + age3 + age0 + age2 + age1 + '\n')
    file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(name0 + age1 + '\n')
    file.write(name0 + age1 + age2 + '\n')
    file.write(name0 + age1 + age2 + age3 + '\n')
    file.write(name0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name3 + age2 + age3 + age1 + '\n')
    file.write(name3 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + age0 + '\n')
    file.write(name2 + age2 + age1 + age0 + age3 + '\n')
    file.write(name2 + age2 + age0 + age1 + age3 + '\n')
    file.write(name2 + age2 + age0 + age3 + age1 + '\n')
    file.write(name2 + age2 + age3 + age1 + age0 + '\n')
    file.write(name2 + age2 + age3 + age0 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + age0 + '\n')
    file.write(name2 + age3 + age2 + age0 + age1 + '\n')
    file.write(name2 + age3 + age1 + age0 + age2 + '\n')
    file.write(name2 + age3 + age1 + age2 + age0 + '\n')
    file.write(name2 + age3 + age0 + age2 + age1 + '\n')
    file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
    
    
    
   
 
else:
    file.write(name0 + secname0 + '\n')
    file.write(name0 + secname0 + age0 + '\n')
    file.write(name0 + secname0 + age0 + age1 + '\n')
    file.write(name0 + secname0 + age0 + age1 + age2 + '\n')
    file.write(name1 + secname1 + '\n')
    file.write(name2 + secname1 + '\n')
    file.write(name2 + age3 + '\n')
    file.write(name2 + secname2 + age2 + '\n')
    file.write(name2 + secname2 + age2 + age3 + '\n')
    file.write(name2 + secname2 + age2 + age3 + age4 + '\n')
    file.write(name2 + secname2 + age2 + age3 + age4 + age5 + '\n')
    file.write(secname2 + name2 + age2 + age3 + age4 + age5 + '\n')
    file.write(secname2 + name2 + age3 + age2 + age4 + age5 + '\n')
    file.write(secname1 + name1 + age3 + age2 + age4 + age5 + '\n')
    file.write(secname1 + name1 + age3 + age4 + age5 + '\n')
   
   
    file.write(email + secname1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + name2 + '\n')
    file.write(email + age1 + name2 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name2 + age1 + '\n')
    file.write(name2 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + '\n')
    file.write(name2 + age1 + age3 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + '\n')
    file.write(name2 + age2 + age3 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + '\n')
    file.write(name2 + age3 + age1 + age2 + '\n')
    file.write(name2 + age0 + age1 + age2 + age3 + '\n')
    file.write(name2 + age0 + age1 + age3 + age2 + '\n')
    file.write(name2 + age0 + age2 + age1 + age3 + '\n')
    file.write(name2 + age0 + age2 + age3 + age1 + '\n')
    file.write(name2 + age0 + age3 + age2 + age1 + '\n')
    file.write(name2 + age0 + age3 + age1 + age2 + '\n')
    file.write(name2 + age1 + age2 + age3 + age0 + '\n')
    file.write(name2 + age1 + age3 + age2 + age0 + '\n')
    file.write(name2 + age1 + age2 + age0 + age3 + '\n')
    file.write(name2 + age1 + age3 + age0 + age2 + '\n')
    file.write(name2 + age2 + age1 + age3 + age0 + '\n')
    file.write(name2 + age2 + age1 + age0 + age3 + '\n')
    file.write(name2 + age2 + age0 + age1 + age3 + '\n')
    file.write(name2 + age2 + age0 + age3 + age1 + '\n')
    file.write(name2 + age2 + age3 + age1 + age0 + '\n')
    file.write(name2 + age2 + age3 + age0 + age1 + '\n')
    file.write(name2 + age3 + age2 + age1 + age0 + '\n')
    file.write(name2 + age3 + age2 + age0 + age1 + '\n')
    file.write(name2 + age3 + age1 + age0 + age2 + '\n')
    file.write(name2 + age3 + age1 + age2 + age0 + '\n')
    file.write(name2 + age3 + age0 + age2 + age1 + '\n')
    file.write(name2 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(pet1 + age1 + '\n')
    file.write(pet1 + age1 + age2 + '\n')
    file.write(pet1 + age1 + age2 + age3 + '\n')
    file.write(pet1 + age1 + age3 + age2 + '\n')
    file.write(pet1 + age2 + age1 + age3 + '\n')
    file.write(pet1 + age2 + age3 + age1 + '\n')
    file.write(pet1 + age3 + age2 + age1 + '\n')
    file.write(pet1 + age3 + age1 + age2 + '\n')
    file.write(pet1 + age0 + age1 + age2 + age3 + '\n')
    file.write(pet1 + age0 + age1 + age3 + age2 + '\n')
    file.write(pet1 + age0 + age2 + age1 + age3 + '\n')
    file.write(pet1 + age0 + age2 + age3 + age1 + '\n')
    file.write(pet1 + age0 + age3 + age2 + age1 + '\n')
    file.write(pet1 + age0 + age3 + age1 + age2 + '\n')
    file.write(pet1 + age1 + age2 + age3 + age0 + '\n')
    file.write(pet0 + age1 + age3 + age2 + age0 + '\n')
    file.write(pet0 + age1 + age2 + age0 + age3 + '\n')
    file.write(pet0 + age1 + age3 + age0 + age2 + '\n')
    file.write(pet0 + age2 + age1 + age3 + age0 + '\n')
    file.write(pet0 + age2 + age1 + age0 + age3 + '\n')
    file.write(pet0 + age2 + age0 + age1 + age3 + '\n')
    file.write(pet0 + age2 + age0 + age3 + age1 + '\n')
    file.write(pet0 + age2 + age3 + age1 + age0 + '\n')
    file.write(pet0 + age2 + age3 + age0 + age1 + '\n')
    file.write(pet0 + age3 + age2 + age1 + age0 + '\n')
    file.write(pet0 + age3 + age2 + age0 + age1 + '\n')
    file.write(pet0 + age3 + age1 + age0 + age2 + '\n')
    file.write(pet0 + age3 + age1 + age2 + age0 + '\n')
    file.write(pet0 + age3 + age0 + age2 + age1 + '\n')
    file.write(pet0 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(email + name0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name0 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(email + secname0 + '\n')
    file.write(email + secname0 + secname1 + '\n')
    file.write(email + secname0 + secname1 + secname2 + '\n')
    file.write(email + secname0 + secname2 + secname1 + '\n')
    file.write(email + pet0 + '\n')
    file.write(email + pet1 + '\n')
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n')
    
    file.write(email + name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    file.write(email + secname0 + '\n')
    file.write(email + name1 + '\n')
    file.write(email + name1 + secname1 + '\n')
    file.write(email + age0 + '\n')
    file.write(email + age0 + age1 + '\n')
    file.write(email + age0 + age1 + age2 + '\n')
    file.write(email + age0 + age2 + age1 + '\n')
    file.write(email + age1 + age0 + age2 + '\n')
    file.write(email + age1 + age2 + age0 + '\n')
    file.write(email + age2 + age0 + age1 + '\n')
    file.write(email + age2 + age1 + age0 + '\n')
    file.write(email + age3 + age4 + age5 + '\n')
    file.write(email + age3 + age5 + age4 + '\n')
    file.write(email + age4 + age3 + age5 + '\n')
    file.write(email + age4 + age5 + age3 + '\n')
    file.write(email + age5 + age3 + age4 + '\n')
    file.write(email + age5 + age4 + age3 + '\n')
    file.write(email + age6 + age7 + age8 + '\n')
    file.write(email + age6 + age8 + age7 + '\n')
    file.write(email + age7 + age8 + age6 + '\n')
    file.write(email + age7 + age6 + age8 + '\n')
    file.write(email + age8 + age6 + age7 + '\n')
    file.write(email + age8 + age7 + age6 + '\n')
    
    file.write(name1 + age1 + '\n')
    file.write(name1 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + '\n')
    file.write(name1 + age1 + age3 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + '\n')
    file.write(name1 + age2 + age3 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + '\n')
    file.write(name1 + age3 + age1 + age2 + '\n')
    file.write(name1 + age0 + age1 + age2 + age3 + '\n')
    file.write(name1 + age0 + age1 + age3 + age2 + '\n')
    file.write(name1 + age0 + age2 + age1 + age3 + '\n')
    file.write(name1 + age0 + age2 + age3 + age1 + '\n')
    file.write(name1 + age0 + age3 + age2 + age1 + '\n')
    file.write(name1 + age0 + age3 + age1 + age2 + '\n')
    file.write(name1 + age1 + age2 + age3 + age0 + '\n')
    file.write(name1 + age1 + age3 + age2 + age0 + '\n')
    file.write(name1 + age1 + age2 + age0 + age3 + '\n')
    file.write(name1 + age1 + age3 + age0 + age2 + '\n')
    file.write(name1 + age2 + age1 + age3 + age0 + '\n')
    file.write(name1 + age2 + age1 + age0 + age3 + '\n')
    file.write(name1 + age2 + age0 + age1 + age3 + '\n')
    file.write(name1 + age2 + age0 + age3 + age1 + '\n')
    file.write(name1 + age2 + age3 + age1 + age0 + '\n')
    file.write(name1 + age2 + age3 + age0 + age1 + '\n')
    file.write(name1 + age3 + age2 + age1 + age0 + '\n')
    file.write(name1 + age3 + age2 + age0 + age1 + '\n')
    file.write(name1 + age3 + age1 + age0 + age2 + '\n')
    file.write(name1 + age3 + age1 + age2 + age0 + '\n')
    file.write(name1 + age3 + age0 + age2 + age1 + '\n')
    file.write(name1 + age3 + age0 + age1 + age2 + '\n') 

if start == "3":
  cls()
print(Fore.CYAN + " ")


print("    _/    _/              _/                                              _/  _/              ")
print("   _/    _/    _/_/    _/_/_/_/  _/_/_/      _/_/_/    _/_/_/    _/_/_/  _/  _/    _/    _/   ")  
print("  _/_/_/_/  _/    _/    _/      _/    _/  _/    _/  _/_/      _/_/      _/_/_/_/  _/    _/    ")
print(" _/    _/  _/    _/    _/      _/    _/  _/    _/      _/_/      _/_/      _/    _/    _/     ")
print("_/    _/    _/_/        _/_/  _/_/_/      _/_/_/  _/_/_/    _/_/_/        _/      _/_/_/      ")
print("                             _/                                                               ")
print("                            _/                                                                ") 
print(" ")
print(Fore.GREEN + "         by    @blackravenshackers (telegram) ") 
yourfile="hotpass.txt"
 
 
 
if os.path.isfile(yourfile):
 os.remove(yourfile)
 print(" ")
 print(" ")
 print(Fore.CYAN + "Old dictionary was removed")
  
else:
 print("ERROR: FILE NOT FOUND!" , yourfile, " EXITING...")
elseif:(Fore.RED + "EXITING..........................")
 
